language: android
jdk: oraclejdk8
sudo: required

branches:
  only:
    - master
before_install:
  - 'mkdir -p "$ANDROID_HOME/licenses"'
  - 'echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"'
  - 'echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"'
  - 'echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"'
script:
    - cd sample
    - chmod +x gradlew
    - ./gradlew build check
cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/android/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/android/gradle/wrapper/dists/"
  - "$HOME/android/.gradle/caches/"
  - "$HOME/android/.gradle/wrapper/"

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - tools
    - android-26
    - addon-google_apis-google-26
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
      - 'android.+'
      - 'google.+'
